# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.swift"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
          swift-version: "5.9.2"
    - name: Install gcc
      run: apt-get update && apt-get -y install gcc mono-mcs && rm -rf /var/lib/apt/lists/*
    - name: Build
      run: swift build
    - name: Lint
      run: swift run swiftlint
    - name: Run tests
      run: swift test
