# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.swift"
      - ".github/workflows/swift.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v1
      with:
          swift-version: "5.9.2"
    - uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64
    - name: Build
      run: swift build
    - name: Lint
      run: swift run swiftlint
    - name: Run tests
      run: swift test
